
all:
	go build


test:
	go test


doc:
	markdown-cli -i GeoIpFilter.md -o GeoIpFilter.html -c ../markdown-cfg.json


mkdocs:
	cat GeoIpFilter.md  >>../tmp2
	echo "GeoIpFilter/GeoIpFilter.md" >>../m.list

