
all:
	go build

test:
	go test

doc:
	markdown-cli -i LimitPathTo.md -o LimitPathTo.html -c ../markdown-cfg.json


mkdocs:
	cat LimitPathTo.md  >>../tmp2
	echo "LimitPathTo/LimitPathTo.md" >>../m.list

