
all:
	go build

test:
	go test

doc:
	markdown-cli -i LimitExtensionTo.md -o LimitExtensionTo.html -c ../markdown-cfg.json


mkdocs:
	cat LimitExtensionTo.md  >>../tmp2
	echo "LimitExtensionTo/LimitExtensionTo.md" >>../m.list

