
all:
	go build


test:
	go test


doc:
	markdown-cli -i GoTemplate.md -o GoTemplate.html -c ../markdown-cfg.json


mkdocs:
	cat GoTemplate.md  >>../tmp2
	echo "GoTemplate/GoTemplate.md" >>../m.list

