
all:
	go build


test:
	go test


doc:
	markdown-cli -i InMemoryCache.md -o InMemoryCache.html -c ../markdown-cfg.json


mkdocs:
	cat InMemoryCache.md  >>../tmp2
	echo "InMemoryCache/InMemoryCache.md" >>../m.list

