
all:
	go build


test:
	go test


doc:
	markdown-cli -i DocImageProc.md -o DocImageProc.html -c ../markdown-cfg.json


mkdocs:
	cat DocImageProc.md >>../tmp2
	echo "DocImageProc/DocImageProc.md" >>../m.list

