
all:
	go build


test:
	go test


doc:
	markdown-cli -i RedirToHttps.md -o RedirToHttps.html -c ../markdown-cfg.json


mkdocs:
	cat RedirToHttps.md  >>../tmp2
	echo "RedirToHttps/RedirToHttps.md" >>../m.list

