
\i t_dual.sql
\i t_config.sql
\i t_email_test_id_seq.sql
\i t_email_id_seq.sql
\i t_customer.sql
\i t_user.sql
\i t_ip_ban.sql
\i t_host_id_seq.sql
\i t_host_to_customer.sql
\i t_auth_token.sql
\i t_user.sql
\i s_ip_ban.sql
\i s_get_config_item.sql
\i s_get_xsrf_mode.sql
\i s_get_customer_id_from_url.sql
\i s_nvl.sql
\i s_login.sql
\i s_register_new_user.sql
\i s_logout.sql
\i s_confirm_email.sql
\i s_password_reset.sql
\i s_change_password.sql
\i status_db.sql
\i s_stayLoggedIn.sql
\i s_validate_token.sql
\i s_echo_builtin.sql
\i s_missing_param_test.sql
\i s_validate_auth_token.sql
\i s_validate_logged_in.sql
\i cleanup.sql
\i s_simulate_email.sql
\i s_get_username_from_email.sql
\i t_pwned.sql
\i s_check_pw_valid.sql
