
all:
	go build


test:
	go test


doc:
	markdown-cli -i ErrorTemplate.md -o ErrorTemplate.html -c ../markdown-cfg.json


mkdocs:
	cat ErrorTemplate.md  >>../tmp2
	echo "ErrorTemplate/ErrorTemplate.md" >>../m.list

