
all:
	go build


test:
	go test


doc:
	markdown-cli -i DumpResponse.md -o DumpResponse.html -c ../markdown-cfg.json


mkdocs:
	cat DumpResponse.md  >>../tmp2
	echo "DumpResponse/DumpResponse.md" >>../m.list

