
all:
	go build


test:
	go test


doc:
	markdown-cli -i LoginRequired.md -o LoginRequired.html -c ../markdown-cfg.json


mkdocs:
	cat LoginRequired.md  >>../tmp2
	echo "LoginRequired/LoginRequired.md" >>../m.list

