
all:
	go build


test:
	go test


doc:
	markdown-cli -i DirectoryBrowse.md -o DirectoryBrowse.html -c ../markdown-cfg.json



mkdocs:
	cat DirectoryBrowse.md  >>../tmp2
	echo "DirectoryBrowse/DirectoryBrowse.md" >>../m.list

