
all:
	go build


test:
	go test


doc:
	markdown-cli -i RedisListRaw.md -o RedisListRaw.html -c ../markdown-cfg.json


mkdocs:
	cat RedisListRaw.md  >>../tmp2
	echo "RedisListRaw/RedisListRaw.md" >>../m.list

