
all:
	go build


test:
	go test


doc:
	markdown-cli -i RejectIpAddress.md -o RejectIpAddress.html -c ../markdown-cfg.json


mkdocs:
	cat RejectIpAddress.md  >>../tmp2
	echo "RejectIpAddress/RejectIpAddress.md" >>../m.list

