
all:
	go build


test:
	go test


doc:
	markdown-cli -i RejectDirectory.md -o RejectDirectory.html -c ../markdown-cfg.json



mkdocs:
	cat RejectDirectory.md  >>../tmp2
	echo "RejectDirectory/RejectDirectory.md" >>../m.list

