
all:
	go build


test:
	go test


doc:
	markdown-cli -i SaveInFile.md -o SaveInFile.html -c ../markdown-cfg.json


mkdocs:
	cat SaveInFile.md  >>../tmp2
	echo "SaveInFile/SaveInFile.md" >>../m.list

