
all:
	go build


test:
	go test


doc:
	markdown-cli -i JSONToTable.md -o JSONToTable.html -c ../markdown-cfg.json


mkdocs:
	cat JSONToTable.md  >>../tmp2
	echo "JSONToTable/JSONToTable.md" >>../m.list

