
all:
	go build

test:
	go test

doc:
	markdown-cli -i LimitPathReTo.md -o LimitPathReTo.html -c ../markdown-cfg.json


mkdocs:
	cat LimitPathReTo.md  >>../tmp2
	echo "LimitPathReTo/LimitPathReTo.md" >>../m.list

