
all:
	go build

test:
	go test

doc:
	markdown-cli -i RejectRePath.md -o RejectRePath.html -c ../markdown-cfg.json


mkdocs:
	cat RejectRePath.md  >>../tmp2
	echo "RejectRePath/RejectRePath.md" >>../m.list

