
all:
	go build


test:
	go test


doc:
	markdown-cli -i ErrorReturn.md -o ErrorReturn.html -c ../markdown-cfg.json


mkdocs:
	cat ErrorReturn.md  >>../tmp2
	echo "ErrorReturn/ErrorReturn.md" >>../m.list

