
all:
	go build


test:
	go test


doc:
	markdown-cli -i BasicAuthRedis.md -o BasicAuthRedis.html -c ../markdown-cfg.json


mkdocs:
	cat BasicAuthRedis.md >>../tmp2
	echo "BasicAuthRedis/BasicAuthRedis.md" >>../m.list

